### ISSUE TITLE
Is this a fork of the official AWS gem?

### ISSUE THREAD

**Issue by timuckun** [everydayhero/amazon-kinesis-client-ruby#9]
https://github.com/awslabs/amazon-kinesis-client-ruby/blob/master/aws-kclrb.gemspec

**Comment by colinbankier** [comment]
Hi timuckun,
No it is not. This library was created before awslabs published a ruby client, and provides additional functionality to theirs. It has since been refactored to utilise awslabs/amazon-kinesis-client-ruby as a dependency to eliminate duplication, but retains the additional functionality, such as managing maven dependencies and commands, and enhanced checkpointing behaviour.

**Comment by timuckun** [comment]
Thank you very much for the explanation.
